#!/usr/bin/env node
/**
 * Write the gitignored `tokens.js` the comparison page reads. (MAP-03)
 *
 * The MapKit token is minted here rather than pasted, with `--origin localhost` — measured working against
 * Apple's bootstrap endpoint, and note the port is not part of the origin claim. The Mapbox token is lifted
 * from `.env.local` / `.env`, which is where the dev loop already keeps it.
 *
 * Neither value is secret in the sense that matters — both ship in a client bundle by design — but the file
 * is gitignored anyway, because a credential in git history is a credential you cannot un-publish, and
 * "it was public anyway" is a bad habit to build.
 *
 * Usage:  node scripts/mapkit/imagery-compare/tokens.mjs
 *         MAPKIT_PRIVATE_KEY must be readable; by default it is taken from ~/.keys/AuthKey_<keyId>.p8
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mintMapKitToken } from '../mintToken.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');

function envValue(name) {
    for (const file of ['.env.local', '.env']) {
        const path = join(REPO, file);
        if (!existsSync(path)) continue;
        for (const line of readFileSync(path, 'utf8').split('\n')) {
            const match = line.match(new RegExp(`^${name}=(.+)$`));
            if (match) return match[1].trim();
        }
    }
    return undefined;
}

const keyId = process.env.MAPKIT_KEY_ID || envValue('MAPKIT_KEY_ID');
const teamId = process.env.MAPKIT_TEAM_ID || envValue('MAPKIT_TEAM_ID');
if (!keyId || !teamId) {
    console.error('need MAPKIT_KEY_ID and MAPKIT_TEAM_ID (env or .env). They are repository variables in CI.');
    process.exit(2);
}

const keyPath = process.env.MAPKIT_PRIVATE_KEY_PATH || join(homedir(), '.keys', `AuthKey_${keyId}.p8`);
if (!process.env.MAPKIT_PRIVATE_KEY && !existsSync(keyPath)) {
    console.error(`no private key: set MAPKIT_PRIVATE_KEY, or put the .p8 at ${keyPath}`);
    process.exit(2);
}
const privateKey = process.env.MAPKIT_PRIVATE_KEY?.replace(/\\n/g, '\n') ?? readFileSync(keyPath, 'utf8');

// `localhost` with no port — measured accepted by Apple, and the port is not part of the claim.
const { token, expiresAt } = mintMapKitToken({ keyId, teamId, privateKey, origin: 'localhost', days: 1 });

const mapbox = envValue('VITE_MAPBOX_TOKEN');
if (!mapbox) console.error('warning: no VITE_MAPBOX_TOKEN found — the Mapbox column will be empty');

writeFileSync(join(HERE, 'tokens.js'),
    '// GENERATED by tokens.mjs — gitignored. Do not commit; regenerate instead.\n'
    + `window.TOKENS = ${JSON.stringify({ mapkit: token, mapbox: mapbox ?? null }, null, 2)};\n`);

console.log(`wrote tokens.js — MapKit token expires ${new Date(expiresAt * 1000).toISOString()}`);
console.log(`  mapkit: yes (origin localhost)   mapbox: ${mapbox ? 'yes' : 'NO'}`);
