import Foundation

#if canImport(FoundationModels)
import FoundationModels
#endif

/// M6 — extends the M1 creation flow (COMMERCIALIZATION-PLAN §10): given the days a new journey was
/// seeded with, suggest short evocative-but-factual names ("Summit night", "Rest day by the river")
/// in one guided request.
///
/// Two hard rules, both enforced by pure/testable code here:
///   1. **Never clobber the user's work.** Suggestions apply ONLY to days that still carry their
///      auto-generated placeholder name ("Day 1", "Day 2", …). A day the user renamed by hand, or a
///      day seeded from a GPX waypoint that already carries a real name, is left exactly as it is.
///      (M1's `DraftDay` has no explicit "edited" flag, so the placeholder pattern is the honest
///      signal for "untouched" — see `isAutoGenerated`.)
///   2. Only text metadata is sent — dates, photo counts, median GPS, elevations. No photo bytes.
///
/// Prompt building (`promptComponents(for:)`) is pure; only `generate(...)` touches the session and
/// it is gated behind `#if canImport(FoundationModels)` + `@available(iOS 26.0, *)`.

// MARK: - Input (pure value type)

/// The facts one proposed day is named from.
struct DayNameFacts: Equatable {
    var dayNumber: Int
    var dateLabel: String?
    var elevation: Int
    /// Median `[lng, lat]` for the day (may be empty when no geotagged data).
    var coordinates: [Double]
    var photoCount: Int

    init(dayNumber: Int, dateLabel: String? = nil, elevation: Int = 0,
         coordinates: [Double] = [], photoCount: Int = 0) {
        self.dayNumber = dayNumber
        self.dateLabel = dateLabel
        self.elevation = elevation
        self.coordinates = coordinates
        self.photoCount = photoCount
    }

    /// Derive the facts from an M1 `DraftDay` at a given list position. `photoCount` is passed in
    /// because `DraftDay` doesn't carry it (it's known transiently at seeding time); 0 is fine.
    init(index: Int, day: DraftDay, photoCount: Int = 0) {
        self.dayNumber = index + 1
        self.dateLabel = day.dateLabel
        self.elevation = day.elevation
        self.coordinates = day.coordinates
        self.photoCount = photoCount
    }
}

// MARK: - Naming logic (pure)

enum DayNamer {

    /// System instructions — same anti-invention posture as the day-note drafter, tuned for short
    /// labels rather than prose.
    static let instructions = """
    You name days of a trek for a travel journaling app. For each day, produce a short title of 2 to \
    4 words — evocative but strictly factual, grounded only in the data given (elevation, date, \
    location, how many photos). Never invent place names or events. No punctuation at the end, no \
    quotation marks. Return exactly one name per day, in the same order as the days given.
    """

    /// The compact, deterministic prompt for a set of days. Contains only text metadata; never any
    /// photo path or byte.
    static func promptComponents(for days: [DayNameFacts]) -> String {
        var lines: [String] = []
        lines.append("Name each of these \(days.count) day(s). Return one short name per day, in order:")
        for day in days {
            var parts: [String] = ["Day \(day.dayNumber)"]
            if let dateLabel = day.dateLabel, !dateLabel.isEmpty { parts.append(dateLabel) }
            if day.elevation > 0 { parts.append("\(day.elevation) m elevation") }
            if day.coordinates.count >= 2 {
                parts.append("near \(coordinate(day.coordinates[1])), \(coordinate(day.coordinates[0]))")
            }
            if day.photoCount > 0 { parts.append("\(day.photoCount) photo(s)") }
            lines.append("- " + parts.joined(separator: ", "))
        }
        return lines.joined(separator: "\n")
    }

    /// POSIX-formatted coordinate (4 dp) so the prompt is byte-stable across locales.
    static func coordinate(_ value: Double) -> String {
        String(format: "%.4f", locale: Locale(identifier: "en_US_POSIX"), value)
    }

    // MARK: Only-rename-unedited merge

    /// The auto-generated placeholder pattern M1 assigns: "Day 1", "Day 2", … (see
    /// `JourneyDraft.days(fromPhotos:)` and `NewJourneySheet.addDay`).
    static func isAutoGenerated(name: String) -> Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix("Day ") else { return false }
        let suffix = trimmed.dropFirst("Day ".count)
        return !suffix.isEmpty && suffix.allSatisfy { $0.isNumber }
    }

    /// Indices of `days` still carrying an auto-generated name (safe to rename).
    static func renamableIndices(in days: [DraftDay]) -> [Int] {
        days.enumerated().compactMap { index, day in
            isAutoGenerated(name: day.name) ? index : nil
        }
    }

    /// Apply `suggestions` to `days`, renaming ONLY days that still carry an auto-generated name and
    /// leaving hand-edited / GPX-named days untouched.
    ///
    /// `suggestions` is positional over the FULL day list (one entry per day, same order as the
    /// prompt). A blank or whitespace-only suggestion is ignored (the day keeps its current name).
    static func applying(suggestions: [String], to days: [DraftDay]) -> [DraftDay] {
        applying(suggestions: suggestions, forDayIDs: days.map(\.id), to: days)
    }

    /// Apply `suggestions` **by day identity**, not by list position.
    ///
    /// `suggestions[i]` was generated from the day whose id is `ids[i]` (captured when the request
    /// was made). Applying by id means that if the user deletes, reorders, or adds a day WHILE the
    /// on-device model is running, each surviving day still receives the name generated from ITS OWN
    /// facts — never a name computed from a different day that happens to now sit at that index. A
    /// day that vanished is skipped; a day added since the request gets no suggestion; and, as
    /// before, only days still carrying an auto-generated placeholder name are renamed.
    /// (quality gate: day-name suggestions applied positionally to a mutable list.)
    static func applying(suggestions: [String], forDayIDs ids: [String], to days: [DraftDay]) -> [DraftDay] {
        var byID: [String: String] = [:]
        for (index, id) in ids.enumerated() where index < suggestions.count {
            byID[id] = suggestions[index]
        }
        var result = days
        for index in result.indices {
            guard let suggestion = byID[result[index].id] else { continue }   // vanished / new day
            guard isAutoGenerated(name: result[index].name) else { continue } // hand-edited
            let trimmed = suggestion.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { continue }
            result[index].name = trimmed
        }
        return result
    }
}

// MARK: - Live generation (gated)

#if canImport(FoundationModels)

/// The `@Generable` output shape: one name per day, in order. iOS 26+ only.
@available(iOS 26.0, *)
@Generable
struct DayNameSuggestions {
    @Guide(description: "One short evocative-but-factual day name (2 to 4 words) per day, in the same order as the days given.")
    var names: [String]
}

@available(iOS 26.0, *)
extension DayNamer {
    /// Generate one name per day on-device. Returns the raw suggestions in order; the caller merges
    /// them with `applying(suggestions:to:)` so only untouched days are renamed. Callers must have
    /// confirmed `Intelligence.isAvailable` first.
    static func generate(for days: [DayNameFacts]) async throws -> [String] {
        let session = LanguageModelSession(instructions: instructions)
        let response = try await session.respond(
            to: promptComponents(for: days),
            generating: DayNameSuggestions.self)
        return response.content.names
    }
}

#endif
