import Foundation

// MARK: - Draft day

/// A proposed day/camp while a journey is being built. Turned into a `Camp` on create
/// (`dayNumber` = position + 1). Coordinates are `[lng, lat]` (GeoJSON order) and may be empty
/// for a manual day the user hasn't placed yet.
struct DraftDay: Identifiable, Equatable {
    /// Where this day came from — drives copy and lets the UI badge auto-proposed rows.
    enum Source: Equatable { case gpxWaypoint, photoCluster, manual }

    var id: String = UUID().uuidString
    var name: String
    var elevation: Int = 0
    var coordinates: [Double] = []      // [lng, lat]
    var dateLabel: String?
    var notes: String = ""
    var source: Source = .manual

    // Enrichment carried from accepted suggestions (weather / POIs / grounded facts). All optional
    // so every existing call site and the memberwise initialiser are unaffected; `makeJourney`
    // forwards them onto the created `Camp`.
    var weather: WeatherData?
    var pointsOfInterest: [PointOfInterest]?
    var funFacts: [FunFact]?
    var historicalSites: [HistoricalSite]?
}

// MARK: - Draft

/// A journey being created from scratch. Route is optional and a draft with no route and no days
/// is still valid (a photos-only trip). The static proposal + stats engine below is pure and
/// heavily unit-tested; the UI (`NewJourneySheet`) is a thin editor over this value.
struct JourneyDraft: Equatable {
    /// Stable identity, minted up front so photo files ingested before create already key to it.
    var id: String = UUID().uuidString.lowercased()
    var name: String = ""
    var country: String = ""
    var description: String = ""
    var dateStarted: Date?
    var dateEnded: Date?
    /// Optional route (GeoJSON LineString, `[lng, lat, ele?]`). `nil` = no route yet.
    var route: Route?
    var days: [DraftDay] = []

    /// S2: carried straight through to the created `Journey` rather than left for `makeJourney`
    /// to hardcode. Every draft today is a "trek" — C1 asks one creation question, not a
    /// taxonomy pick — but the field is honest all the way from here, so S4's inference has
    /// somewhere real to write.
    var journeyType: String = "trek"

    /// A journey needs at least a name; everything else (route, days, dates) is optional.
    var isValid: Bool { !name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }

    var hasRoute: Bool { (route?.coordinates.isEmpty == false) }

    // MARK: Day proposal

    /// Whether the current day list is safe to REPLACE with a fresh auto-seed — i.e. every day is
    /// an untouched auto-proposal and the user has neither added a manual day nor renamed a
    /// placeholder. Used by "Replace route" so a wrong first import can be corrected (its stale days
    /// swapped for the new file's), while a day list the user has actually worked on is never
    /// clobbered. `DraftDay.source` exists precisely to make this distinction.
    /// (quality gate: replace route keeps stale auto-seeded days.)
    static func daysAreAllAutoSeeded(_ days: [DraftDay]) -> Bool {
        !days.isEmpty && days.allSatisfy { day in
            switch day.source {
            case .manual:
                return false   // a hand-added day means the user has started building the list
            case .gpxWaypoint:
                return true    // its name/facts came from the file now being replaced
            case .photoCluster:
                return DayNamer.isAutoGenerated(name: day.name)   // still the "Day N" placeholder
            }
        }
    }

    /// One day per GPX waypoint, in document order (name, elevation, coordinates, date).
    static func days(fromWaypoints waypoints: [GPXWaypoint]) -> [DraftDay] {
        waypoints.enumerated().map { index, wpt in
            let name = wpt.name?.trimmingCharacters(in: .whitespacesAndNewlines)
            return DraftDay(
                name: (name?.isEmpty == false ? name! : "Day \(index + 1)"),
                elevation: wpt.elevation.map { Int($0.rounded()) } ?? 0,
                coordinates: wpt.coordinates.count >= 2 ? [wpt.coordinates[0], wpt.coordinates[1]] : [],
                dateLabel: wpt.time.map(Self.dateLabel(from:)),
                notes: wpt.desc?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "",
                source: .gpxWaypoint)
        }
    }

    /// PhotoDayMatcher in reverse: cluster photos by calendar day (UTC), then propose Day 1…N in
    /// chronological order. Each day's coordinates are the median of that day's geotagged photos
    /// (empty when none carry GPS). Photos with no `takenAt` are ignored (they can't seed a day).
    /// Thin wrapper over `daysWithAssignments(fromPhotos:)` for callers that don't need the mapping.
    static func days(fromPhotos photos: [Photo]) -> [DraftDay] {
        daysWithAssignments(fromPhotos: photos).days
    }

    /// Sibling of `days(fromPhotos:)` that also reports which day each photo landed in (photo id →
    /// `DraftDay.id`). `makeJourney` carries a `DraftDay`'s `id` onto its `Camp` unchanged, so this
    /// mapping is still a valid `waypointId` once the journey is created — no id-translation step
    /// needed at create time. (C2: stamping this straight onto each staged `Photo.waypointId` is
    /// what lets photos land on the right day the moment the journey is made.)
    static func daysWithAssignments(fromPhotos photos: [Photo])
        -> (days: [DraftDay], assignments: [String: String]) {
        var buckets: [String: [Photo]] = [:]
        for photo in photos {
            guard let date = PhotoDayMatcher.parseDate(photo.takenAt) else { continue }
            buckets[dayKey(from: date), default: []].append(photo)
        }
        var assignments: [String: String] = [:]
        let days: [DraftDay] = buckets.keys.sorted().enumerated().map { index, key in
            let bucket = buckets[key] ?? []
            let coords = medianCoordinate(bucket.compactMap { $0.coordinates })
            let day = DraftDay(
                name: "Day \(index + 1)",
                coordinates: coords ?? [],
                dateLabel: displayLabel(fromDayKey: key),
                source: .photoCluster)
            for photo in bucket { assignments[photo.id] = day.id }
            return day
        }
        return (days, assignments)
    }

    /// Clear `waypointId` on any photo pointing at a day no longer present in `days` — used when
    /// the user deletes a proposed day in the review screen: its photos stay staged, just
    /// unassigned, never deleted. Pure/testable so the view's day-removal action is a one-liner.
    static func unassignPhotos(_ photos: [Photo], keeping days: [DraftDay]) -> [Photo] {
        let survivingIDs = Set(days.map(\.id))
        return photos.map { photo in
            guard let waypointId = photo.waypointId, !survivingIDs.contains(waypointId) else { return photo }
            var photo = photo
            photo.waypointId = nil
            return photo
        }
    }

    // MARK: Stats

    /// Elevation gain/loss over a route, in metres, with a small smoothing threshold so GPS
    /// jitter doesn't inflate the totals. Hysteresis: a running reference elevation only advances
    /// once the signal moves more than `smoothing` from it, and each such move is booked as gain
    /// or loss. Points without a finite elevation are skipped.
    static func elevationGainLoss(route: [RouteCoordinate], smoothing: Double = 3.0) -> (gain: Int, loss: Int) {
        var reference: Double?
        var gain = 0.0
        var loss = 0.0
        for coordinate in route where coordinate.count >= 3 {
            let elevation = coordinate[2]
            guard elevation.isFinite else { continue }
            guard let ref = reference else { reference = elevation; continue }
            let delta = elevation - ref
            if abs(delta) < smoothing { continue }
            if delta > 0 { gain += delta } else { loss += -delta }
            reference = elevation
        }
        return (Int(gain.rounded()), Int(loss.rounded()))
    }

    /// Great-circle length of the route in km (Haversine over consecutive `[lng, lat]` points).
    static func totalDistanceKm(route: [RouteCoordinate]) -> Double {
        guard route.count > 1 else { return 0 }
        var total = 0.0
        for i in 1..<route.count {
            let a = route[i - 1], b = route[i]
            guard a.count >= 2, b.count >= 2 else { continue }
            total += PhotoDayMatcher.distanceKm(a[1], a[0], b[1], b[0])
        }
        return total
    }

    /// Highest point of the route (max elevation), named after the journey.
    static func highestPoint(route: [RouteCoordinate], name: String) -> HighestPoint? {
        var best: [Double]?
        for coordinate in route where coordinate.count >= 3 && coordinate[2].isFinite {
            if best == nil || coordinate[2] > best![2] { best = coordinate }
        }
        guard let best else { return nil }
        return HighestPoint(name: name.isEmpty ? "Highest point" : name,
                            elevation: Int(best[2].rounded()),
                            coordinates: [best[0], best[1]])
    }

    /// Duration in days: the day count when days exist, else the inclusive date span, else 0.
    static func duration(dayCount: Int, dateStarted: Date?, dateEnded: Date?) -> Int {
        if dayCount > 0 { return dayCount }
        if let start = dateStarted, let end = dateEnded, end >= start {
            return Int(floor(end.timeIntervalSince(start) / 86_400)) + 1
        }
        return 0
    }

    /// Auto-computed stats for the draft (distance / elevation from the route when present,
    /// duration from days or dates).
    static func computeStats(route: Route?, days: [DraftDay],
                             dateStarted: Date?, dateEnded: Date?, name: String) -> TrekStats {
        let coordinates = route?.coordinates ?? []
        let distance = (totalDistanceKm(route: coordinates) * 10).rounded() / 10
        let (gain, loss) = elevationGainLoss(route: coordinates)
        return TrekStats(
            duration: duration(dayCount: days.count, dateStarted: dateStarted, dateEnded: dateEnded),
            totalDistance: distance,
            totalElevationGain: gain,
            totalElevationLoss: coordinates.isEmpty ? nil : loss,
            highestPoint: highestPoint(route: coordinates, name: name))
    }

    // MARK: Build

    /// Materialise the draft into a domain `Journey` ready for persistence. `existingSlugs`
    /// uniquifies the generated slug. Per-day route stats are (re)derived on read by
    /// `CoreDataMapping`/`DayStats`, so camps carry only the authored fields here.
    func makeJourney(existingSlugs: [String] = []) -> Journey {
        let trimmedName = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let slug = Self.uniqueSlug(from: trimmedName, existing: existingSlugs)
        let theRoute = route ?? .empty

        let camps: [Camp] = days.enumerated().map { index, day in
            let dayName = day.name.trimmingCharacters(in: .whitespacesAndNewlines)
            return Camp(
                id: day.id,
                name: dayName.isEmpty ? "Day \(index + 1)" : dayName,
                dayNumber: index + 1,
                elevation: day.elevation,
                coordinates: day.coordinates,
                notes: day.notes,
                highlights: [],
                terrain: nil,
                timeFromPrevious: nil,
                dateLabel: day.dateLabel,
                routePointIndex: nil,
                routeDistanceKm: nil,
                weather: day.weather,
                funFacts: day.funFacts,
                pointsOfInterest: day.pointsOfInterest,
                historicalSites: day.historicalSites)
        }

        let stats = Self.computeStats(route: route, days: days,
                                      dateStarted: dateStarted, dateEnded: dateEnded,
                                      name: trimmedName)

        return Journey(
            id: id,
            slug: slug,
            name: trimmedName,
            country: country.trimmingCharacters(in: .whitespacesAndNewlines),
            description: description.trimmingCharacters(in: .whitespacesAndNewlines),
            heroImageURL: nil,
            dateStarted: DateOnly.string(from: dateStarted),
            dateEnded: DateOnly.string(from: dateEnded),
            isPublic: false,
            journeyType: journeyType,
            summitElevation: stats.highestPoint?.elevation,
            totalDistance: stats.totalDistance,
            totalDays: stats.duration,
            centerCoordinates: nil,
            preferredBearing: nil,
            preferredPitch: nil,
            stats: stats,
            route: theRoute,
            camps: camps)
    }

    // MARK: - Slug

    /// kebab-case an arbitrary name into an URL-safe slug (ASCII letters/digits, dash-separated).
    static func slugify(_ name: String) -> String {
        let folded = name.folding(options: [.diacriticInsensitive, .caseInsensitive],
                                  locale: Locale(identifier: "en_US_POSIX"))
        var out = ""
        var lastWasDash = false
        for scalar in folded.unicodeScalars {
            let ch = Character(scalar)
            if scalar.isASCII && (ch.isLetter || ch.isNumber) {
                out.append(Character(ch.lowercased()))
                lastWasDash = false
            } else if !lastWasDash {
                out.append("-")
                lastWasDash = true
            }
        }
        let trimmed = out.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
        return trimmed.isEmpty ? "journey" : trimmed
    }

    /// Slug for `name`, suffixed `-2`, `-3`… until it doesn't collide with `existing`.
    static func uniqueSlug(from name: String, existing: [String]) -> String {
        let base = slugify(name)
        let taken = Set(existing)
        guard taken.contains(base) else { return base }
        var suffix = 2
        while taken.contains("\(base)-\(suffix)") { suffix += 1 }
        return "\(base)-\(suffix)"
    }

    // MARK: - Date / clustering helpers

    /// UTC `yyyy-MM-dd` bucket key (sorts chronologically as a plain string).
    static func dayKey(from date: Date) -> String {
        Self.keyFormatter.string(from: date)
    }

    /// Median `[lng, lat]` of a set of coordinates (per-axis median), or nil when empty.
    static func medianCoordinate(_ coordinates: [[Double]]) -> [Double]? {
        let valid = coordinates.filter { $0.count >= 2 }
        guard !valid.isEmpty else { return nil }
        let lngs = valid.map { $0[0] }.sorted()
        let lats = valid.map { $0[1] }.sorted()
        return [median(lngs), median(lats)]
    }

    private static func median(_ sorted: [Double]) -> Double {
        let count = sorted.count
        if count % 2 == 1 { return sorted[count / 2] }
        return (sorted[count / 2 - 1] + sorted[count / 2]) / 2
    }

    /// Human date label for a day, e.g. "29 Sep 2023" (UTC).
    static func dateLabel(from date: Date) -> String {
        Self.labelFormatter.string(from: date)
    }

    /// Inverse of `dateLabel(from:)` — parse "29 Sep 2023" back to a UTC date (nil if it doesn't
    /// match). Lets weather enrichment recover a real date from a photo-seeded day's label.
    static func date(fromDayLabel label: String?) -> Date? {
        guard let label, !label.isEmpty else { return nil }
        return labelFormatter.date(from: label)
    }

    /// The best date for a draft day: the journey start plus the day offset when a start is set,
    /// otherwise the day's own label. Used to fetch that day's historical weather.
    static func weatherDate(dayIndex: Int, dateLabel: String?, dateStarted: Date?) -> Date? {
        if let dateStarted {
            return dateStarted.addingTimeInterval(Double(dayIndex) * 86_400)
        }
        return date(fromDayLabel: dateLabel)
    }

    // MARK: - C4: auto dates (from photo clusters / GPX times)

    /// `dateStarted`/`dateEnded` from an already-clustered day list — the first/last dated day, in
    /// UTC (via `date(fromDayLabel:)`, so this stays in lockstep with the label the Days section
    /// itself shows). Works for both photo-clustered days (`daysWithAssignments`) and GPX-waypoint
    /// days, since both carry a `dateLabel`; a manual day or a photo-cluster day with no readable
    /// capture date (never happens today, but is a valid `DraftDay`) simply doesn't contribute an
    /// endpoint. Nil when nothing in the list carries a date — the review screen then reads
    /// "Add dates" instead of a derived range.
    static func dateRange(fromDays days: [DraftDay]) -> (start: Date, end: Date)? {
        let dated = days.compactMap { date(fromDayLabel: $0.dateLabel) }
        guard let start = dated.min(), let end = dated.max() else { return nil }
        return (start, end)
    }

    /// `dateStarted`/`dateEnded` straight from a parsed GPX file's own time signals, independent of
    /// whether its waypoints were actually seeded into the day list (a user who already built a day
    /// list keeps it on "Replace route" — see `applying(_:toDays:)` — but the file's dates are still
    /// honest information about when the trip happened). Prefers the earliest/latest `<wpt><time>`;
    /// falls back to the single `<metadata><time>` (same instant for both ends) for a track that
    /// carries no per-waypoint times — including a trackpoint-only file, since `GPXParser` doesn't
    /// retain per-point times yet (C9). Nil when the file carries no time information at all.
    static func dateRange(fromGPX file: GPXFile) -> (start: Date, end: Date)? {
        let waypointTimes = file.waypoints.compactMap(\.time)
        if let start = waypointTimes.min(), let end = waypointTimes.max() {
            return (start, end)
        }
        if let time = file.time { return (time, time) }
        return nil
    }

    // MARK: - C3: name-suggestion chip

    /// The review screen's "Use \"Tanzania, September 2023\"" chip — country plus the month/year of
    /// the earliest dated day. Nil whenever there's nothing worth suggesting, which INCLUDES the
    /// name field already carrying something: the chip must never appear (let alone fire) once the
    /// user has typed a name, so that guard lives here rather than only at the call site, keeping the
    /// whole rule in one testable place.
    static func nameSuggestion(currentName: String, country: String, firstDayDateLabel: String?) -> String? {
        guard currentName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        let trimmedCountry = country.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedCountry.isEmpty, let date = date(fromDayLabel: firstDayDateLabel) else { return nil }
        return "\(trimmedCountry), \(monthYearFormatter.string(from: date))"
    }

    private static func displayLabel(fromDayKey key: String) -> String? {
        guard let date = keyFormatter.date(from: key) else { return nil }
        return labelFormatter.string(from: date)
    }

    private static let keyFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "yyyy-MM-dd"
        return f
    }()

    private static let labelFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "d MMM yyyy"
        return f
    }()

    private static let monthYearFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "MMMM yyyy"
        return f
    }()
}
